export function getLangCodeForVoiceId(voiceId: string): string {
  if (voiceId.startsWith("English_")) return "EN";
  if (voiceId.startsWith("Chinese (Mandarin)_")) return "ZH";
  if (voiceId === "Arrogant_Miss" || voiceId === "Robot_Armor") return "ZH";
  if (voiceId.startsWith("Japanese_")) return "JA";
  if (voiceId.startsWith("Cantonese_")) return "YUE";
  if (voiceId.startsWith("Korean_")) return "KO";
  if (voiceId.startsWith("Spanish_")) return "ES";
  if (voiceId.startsWith("Portuguese_")) return "PT";
  if (voiceId.startsWith("French_")) return "FR";
  if (voiceId.startsWith("Indonesian_")) return "ID";
  if (voiceId.startsWith("German_")) return "DE";
  if (voiceId.startsWith("Russian_")) return "RU";
  if (voiceId.startsWith("Italian_")) return "IT";
  if (voiceId.startsWith("Dutch_")) return "NL";
  if (voiceId.startsWith("Vietnamese_")) return "VI";
  if (voiceId.startsWith("Arabic_")) return "AR";
  if (voiceId.startsWith("Turkish_")) return "TR";
  if (voiceId.startsWith("Ukrainian_")) return "UK";
  if (voiceId.startsWith("Thai_")) return "TH";
  if (voiceId.startsWith("Polish_")) return "PL";
  if (voiceId.startsWith("Romanian_")) return "RO";
  if (voiceId.startsWith("greek_") || voiceId.startsWith("Greek_")) return "EL";
  if (voiceId.startsWith("czech_") || voiceId.startsWith("Czech_")) return "CS";
  if (voiceId.startsWith("finnish_")) return "FI";
  if (voiceId.startsWith("hindi_")) return "HI";
  return "";
}

export const RAW_MINIMAX_VOICES = [
  { label: "Expressive Narrator", value: "English_expressive_narrator" },
  { label: "Radiant Girl", value: "English_radiant_girl" },
  { label: "Magnetic-voiced Male", value: "English_magnetic_voiced_man" },
  { label: "Compelling Lady", value: "English_compelling_lady1" },
  { label: "Aussie Bloke", value: "English_Aussie_Bloke" },
  { label: "Captivating Female", value: "English_captivating_female1" },
  { label: "Upbeat Woman", value: "English_Upbeat_Woman" },
  { label: "Trustworthy Man", value: "English_Trustworth_Man" },
  { label: "Calm Woman", value: "English_CalmWoman" },
  { label: "Upset Girl", value: "English_UpsetGirl" },
  { label: "Gentle-voiced Man", value: "English_Gentle-voiced_man" },
  { label: "Whispering girl", value: "English_Whispering_girl" },
  { label: "Diligent Man", value: "English_Diligent_Man" },
  { label: "Graceful Lady", value: "English_Graceful_Lady" },
  { label: "Reserved Young Man", value: "English_ReservedYoungMan" },
  { label: "Playful Girl", value: "English_PlayfulGirl" },
  { label: "Man With Deep Voice", value: "English_ManWithDeepVoice" },
  { label: "Mature Partner", value: "English_MaturePartner" },
  { label: "Friendly Guy", value: "English_FriendlyPerson" },
  { label: "Bossy Lady", value: "English_MatureBoss" },
  { label: "Male Debater", value: "English_Debator" },
  { label: "Lovely Girl", value: "English_LovelyGirl" },
  { label: "Reliable Man", value: "English_Steadymentor" },
  { label: "Deep-voiced Gentleman", value: "English_Deep-VoicedGentleman" },
  { label: "Wise Lady", value: "English_Wiselady" },
  { label: "Captivating Storyteller", value: "English_CaptivatingStoryteller" },
  { label: "Decent Young Man", value: "English_DecentYoungMan" },
  { label: "Sentimental Lady", value: "English_SentimentalLady" },
  { label: "Imposing Queen", value: "English_ImposingManner" },
  { label: "Teen Boy", value: "English_SadTeen" },
  { label: "Passionate Warrior", value: "English_PassionateWarrior" },
  { label: "Wise Scholar", value: "English_WiseScholar" },
  { label: "Soft-Spoken Girl", value: "English_Soft-spokenGirl" },
  { label: "Serene Woman", value: "English_SereneWoman" },
  { label: "Confident Woman", value: "English_ConfidentWoman" },
  { label: "Patient Man", value: "English_PatientMan" },
  { label: "Comedian", value: "English_Comedian" },
  { label: "Bossy Leader", value: "English_BossyLeader" },
  { label: "Strong-Willed Boy", value: "English_Strong-WilledBoy" },
  { label: "Stressed Lady", value: "English_StressedLady" },
  { label: "Assertive Queen", value: "English_AssertiveQueen" },
  { label: "Female Narrator", value: "English_AnimeCharacter" },
  { label: "Jovial Man", value: "English_Jovialman" },
  { label: "Whimsical Girl", value: "English_WhimsicalGirl" },
  { label: "Kind-Hearted Girl", value: "English_Kind-heartedGirl" },
  {
    label: "Reliable Executive",
    value: "Chinese (Mandarin)_Reliable_Executive",
  },
  { label: "News Anchor", value: "Chinese (Mandarin)_News_Anchor" },
  {
    label: "Unrestrained Young Man",
    value: "Chinese (Mandarin)_Unrestrained_Young_Man",
  },
  { label: "Mature Woman", value: "Chinese (Mandarin)_Mature_Woman" },
  { label: "Arrogant Miss", value: "Arrogant_Miss" },
  { label: "Robot Armor", value: "Robot_Armor" },
  {
    label: "Kind-hearted Antie",
    value: "Chinese (Mandarin)_Kind-hearted_Antie",
  },
  {
    label: "HK Flight Attendant",
    value: "Chinese (Mandarin)_HK_Flight_Attendant",
  },
  { label: "Humorous Elder", value: "Chinese (Mandarin)_Humorous_Elder" },
  { label: "Gentleman", value: "Chinese (Mandarin)_Gentleman" },
  { label: "Warm Bestie", value: "Chinese (Mandarin)_Warm_Bestie" },
  { label: "Stubborn Friend", value: "Chinese (Mandarin)_Stubborn_Friend" },
  { label: "Sweet Lady", value: "Chinese (Mandarin)_Sweet_Lady" },
  {
    label: "Southern Young Man",
    value: "Chinese (Mandarin)_Southern_Young_Man",
  },
  { label: "Wise Women", value: "Chinese (Mandarin)_Wise_Women" },
  { label: "Gentle Youth", value: "Chinese (Mandarin)_Gentle_Youth" },
  { label: "Warm Girl", value: "Chinese (Mandarin)_Warm_Girl" },
  { label: "Male Announcer", value: "Chinese (Mandarin)_Male_Announcer" },
  {
    label: "Kind-hearted Elder",
    value: "Chinese (Mandarin)_Kind-hearted_Elder",
  },
  { label: "Cute Spirit", value: "Chinese (Mandarin)_Cute_Spirit" },
  { label: "Radio Host", value: "Chinese (Mandarin)_Radio_Host" },
  { label: "Lyrical Voice", value: "Chinese (Mandarin)_Lyrical_Voice" },
  {
    label: "Straightforward Boy",
    value: "Chinese (Mandarin)_Straightforward_Boy",
  },
  { label: "Sincere Adult", value: "Chinese (Mandarin)_Sincere_Adult" },
  { label: "Gentle Senior", value: "Chinese (Mandarin)_Gentle_Senior" },
  { label: "Crisp Girl", value: "Chinese (Mandarin)_Crisp_Girl" },
  { label: "Pure-hearted Boy", value: "Chinese (Mandarin)_Pure-hearted_Boy" },
  { label: "Soft Girl", value: "Chinese (Mandarin)_Soft_Girl" },
  { label: "Intellectual Girl", value: "Chinese (Mandarin)_IntellectualGirl" },
  { label: "Warm-hearted Girl", value: "Chinese (Mandarin)_Warm_HeartedGirl" },
  { label: "Laid-back Girl", value: "Chinese (Mandarin)_Laid_BackGirl" },
  { label: "Explorative Girl", value: "Chinese (Mandarin)_ExplorativeGirl" },
  { label: "Warm-hearted Aunt", value: "Chinese (Mandarin)_Warm-HeartedAunt" },
  { label: "Bashful Girl", value: "Chinese (Mandarin)_BashfulGirl" },
  { label: "Intellectual Senior", value: "Japanese_IntellectualSenior" },
  { label: "Decisive Princess", value: "Japanese_DecisivePrincess" },
  { label: "Loyal Knight", value: "Japanese_LoyalKnight" },
  { label: "Dominant Man", value: "Japanese_DominantMan" },
  { label: "Serious Commander", value: "Japanese_SeriousCommander" },
  { label: "Cold Queen", value: "Japanese_ColdQueen" },
  { label: "Dependable Woman", value: "Japanese_DependableWoman" },
  { label: "Gentle Butler", value: "Japanese_GentleButler" },
  { label: "Kind Lady", value: "Japanese_KindLady" },
  { label: "Calm Lady", value: "Japanese_CalmLady" },
  { label: "Optimistic Youth", value: "Japanese_OptimisticYouth" },
  { label: "Generous Izakaya Owner", value: "Japanese_GenerousIzakayaOwner" },
  { label: "Sporty Student", value: "Japanese_SportyStudent" },
  { label: "Innocent Boy", value: "Japanese_InnocentBoy" },
  { label: "Graceful Maiden", value: "Japanese_GracefulMaiden" },
  {
    label: "Professional Female Host",
    value: "Cantonese_ProfessionalHost（F)",
  },
  { label: "Gentle Lady", value: "Cantonese_GentleLady" },
  { label: "Professional Male Host", value: "Cantonese_ProfessionalHost（M)" },
  { label: "Playful Man", value: "Cantonese_PlayfulMan" },
  { label: "Cute Girl", value: "Cantonese_CuteGirl" },
  { label: "Kind Woman", value: "Cantonese_KindWoman" },
  { label: "Airheaded Girl", value: "Korean_AirheadedGirl" },
  { label: "Athletic Girl", value: "Korean_AthleticGirl" },
  { label: "Athletic Student", value: "Korean_AthleticStudent" },
  { label: "Brave Adventurer", value: "Korean_BraveAdventurer" },
  { label: "Brave Female Warrior", value: "Korean_BraveFemaleWarrior" },
  { label: "Brave Youth", value: "Korean_BraveYouth" },
  { label: "Calm Gentleman", value: "Korean_CalmGentleman" },
  { label: "Calm Lady", value: "Korean_CalmLady" },
  { label: "Caring Woman", value: "Korean_CaringWoman" },
  { label: "Charming Elder Sister", value: "Korean_CharmingElderSister" },
  { label: "Charming Sister", value: "Korean_CharmingSister" },
  { label: "Cheerful Boyfriend", value: "Korean_CheerfulBoyfriend" },
  { label: "Cheerful Cool Junior", value: "Korean_CheerfulCoolJunior" },
  { label: "Cheerful Little Sister", value: "Korean_CheerfulLittleSister" },
  { label: "Childhood Friend Girl", value: "Korean_ChildhoodFriendGirl" },
  { label: "Cocky Guy", value: "Korean_CockyGuy" },
  { label: "Cold Girl", value: "Korean_ColdGirl" },
  { label: "Cold Young Man", value: "Korean_ColdYoungMan" },
  { label: "Confident Boss", value: "Korean_ConfidentBoss" },
  { label: "Considerate Senior", value: "Korean_ConsiderateSenior" },
  { label: "Decisive Queen", value: "Korean_DecisiveQueen" },
  { label: "Dominant Man", value: "Korean_DominantMan" },
  { label: "Elegant Princess", value: "Korean_ElegantPrincess" },
  { label: "Enchanting Sister", value: "Korean_EnchantingSister" },
  { label: "Enthusiastic Teen", value: "Korean_EnthusiasticTeen" },
  { label: "Friendly Big Sister", value: "Korean_FriendlyBigSister" },
  { label: "Gentle Boss", value: "Korean_GentleBoss" },
  { label: "Gentle Woman", value: "Korean_GentleWoman" },
  { label: "Haughty Lady", value: "Korean_HaughtyLady" },
  { label: "Innocent Boy", value: "Korean_InnocentBoy" },
  { label: "Intellectual Man", value: "Korean_IntellectualMan" },
  { label: "Intellectual Senior", value: "Korean_IntellectualSenior" },
  { label: "Lonely Warrior", value: "Korean_LonelyWarrior" },
  { label: "Mature Lady", value: "Korean_MatureLady" },
  { label: "Mysterious Girl", value: "Korean_MysteriousGirl" },
  { label: "Optimistic Youth", value: "Korean_OptimisticYouth" },
  { label: "Playboy Charmer", value: "Korean_PlayboyCharmer" },
  { label: "Possessive Man", value: "Korean_PossessiveMan" },
  { label: "Quirky Girl", value: "Korean_QuirkyGirl" },
  { label: "Reliable Sister", value: "Korean_ReliableSister" },
  { label: "Reliable Youth", value: "Korean_ReliableYouth" },
  { label: "Sassy Girl", value: "Korean_SassyGirl" },
  { label: "Shy Girl", value: "Korean_ShyGirl" },
  { label: "Soothing Lady", value: "Korean_SoothingLady" },
  { label: "Strict Boss", value: "Korean_StrictBoss" },
  { label: "Sweet Girl", value: "Korean_SweetGirl" },
  { label: "Thoughtful Woman", value: "Korean_ThoughtfulWoman" },
  { label: "Wise Elf", value: "Korean_WiseElf" },
  { label: "Wise Teacher", value: "Korean_WiseTeacher" },
  { label: "Serene Woman", value: "Spanish_SereneWoman" },
  { label: "Mature Partner", value: "Spanish_MaturePartner" },
  { label: "Captivating Storyteller", value: "Spanish_CaptivatingStoryteller" },
  { label: "Narrator", value: "Spanish_Narrator" },
  { label: "Wise Scholar", value: "Spanish_WiseScholar" },
  { label: "Kind-hearted Girl", value: "Spanish_Kind-heartedGirl" },
  { label: "Determined Manager", value: "Spanish_DeterminedManager" },
  { label: "Bossy Leader", value: "Spanish_BossyLeader" },
  { label: "Reserved Young Man", value: "Spanish_ReservedYoungMan" },
  { label: "Confident Woman", value: "Spanish_ConfidentWoman" },
  { label: "Thoughtful Man", value: "Spanish_ThoughtfulMan" },
  { label: "Strong-willed Boy", value: "Spanish_Strong-WilledBoy" },
  { label: "Sophisticated Lady", value: "Spanish_SophisticatedLady" },
  { label: "Rational Man", value: "Spanish_RationalMan" },
  { label: "Anime Character", value: "Spanish_AnimeCharacter" },
  { label: "Deep-toned Man", value: "Spanish_Deep-tonedMan" },
  { label: "Fussy hostess", value: "Spanish_Fussyhostess" },
  { label: "Sincere Teen", value: "Spanish_SincereTeen" },
  { label: "Frank Lady", value: "Spanish_FrankLady" },
  { label: "Comedian", value: "Spanish_Comedian" },
  { label: "Debator", value: "Spanish_Debator" },
  { label: "Tough Boss", value: "Spanish_ToughBoss" },
  { label: "Wise Lady", value: "Spanish_Wiselady" },
  { label: "Steady Mentor", value: "Spanish_Steadymentor" },
  { label: "Jovial Man", value: "Spanish_Jovialman" },
  { label: "Santa Claus", value: "Spanish_SantaClaus" },
  { label: "Rudolph", value: "Spanish_Rudolph" },
  { label: "Intonate Girl", value: "Spanish_Intonategirl" },
  { label: "Arnold", value: "Spanish_Arnold" },
  { label: "Ghost", value: "Spanish_Ghost" },
  { label: "Humorous Elder", value: "Spanish_HumorousElder" },
  { label: "Energetic Boy", value: "Spanish_EnergeticBoy" },
  { label: "Whimsical Girl", value: "Spanish_WhimsicalGirl" },
  { label: "Strict Boss", value: "Spanish_StrictBoss" },
  { label: "Reliable Man", value: "Spanish_ReliableMan" },
  { label: "Serene Elder", value: "Spanish_SereneElder" },
  { label: "Angry Man", value: "Spanish_AngryMan" },
  { label: "Assertive Queen", value: "Spanish_AssertiveQueen" },
  { label: "Caring Girlfriend", value: "Spanish_CaringGirlfriend" },
  { label: "Powerful Soldier", value: "Spanish_PowerfulSoldier" },
  { label: "Passionate Warrior", value: "Spanish_PassionateWarrior" },
  { label: "Chatty Girl", value: "Spanish_ChattyGirl" },
  { label: "Romantic Husband", value: "Spanish_RomanticHusband" },
  { label: "Compelling Girl", value: "Spanish_CompellingGirl" },
  { label: "Powerful Veteran", value: "Spanish_PowerfulVeteran" },
  { label: "Sensible Manager", value: "Spanish_SensibleManager" },
  { label: "Thoughtful Lady", value: "Spanish_ThoughtfulLady" },
  { label: "Sentimental Lady", value: "Portuguese_SentimentalLady" },
  { label: "Bossy Leader", value: "Portuguese_BossyLeader" },
  { label: "Wise lady", value: "Portuguese_Wiselady" },
  { label: "Strong-willed Boy", value: "Portuguese_Strong-WilledBoy" },
  { label: "Deep-voiced Gentleman", value: "Portuguese_Deep-VoicedGentleman" },
  { label: "Upset Girl", value: "Portuguese_UpsetGirl" },
  { label: "Passionate Warrior", value: "Portuguese_PassionateWarrior" },
  { label: "Anime Character", value: "Portuguese_AnimeCharacter" },
  { label: "Confident Woman", value: "Portuguese_ConfidentWoman" },
  { label: "Angry Man", value: "Portuguese_AngryMan" },
  {
    label: "Captivating Storyteller",
    value: "Portuguese_CaptivatingStoryteller",
  },
  { label: "Godfather", value: "Portuguese_Godfather" },
  { label: "Reserved Young Man", value: "Portuguese_ReservedYoungMan" },
  { label: "Smart Young Girl", value: "Portuguese_SmartYoungGirl" },
  { label: "Kind-hearted Girl", value: "Portuguese_Kind-heartedGirl" },
  { label: "Pompous lady", value: "Portuguese_Pompouslady" },
  { label: "Grinch", value: "Portuguese_Grinch" },
  { label: "Debator", value: "Portuguese_Debator" },
  { label: "Sweet Girl", value: "Portuguese_SweetGirl" },
  { label: "Attractive Girl", value: "Portuguese_AttractiveGirl" },
  { label: "Thoughtful Man", value: "Portuguese_ThoughtfulMan" },
  { label: "Playful Girl", value: "Portuguese_PlayfulGirl" },
  { label: "Gorgeous Lady", value: "Portuguese_GorgeousLady" },
  { label: "Lovely Lady", value: "Portuguese_LovelyLady" },
  { label: "Serene Woman", value: "Portuguese_SereneWoman" },
  { label: "Sad Teen", value: "Portuguese_SadTeen" },
  { label: "Mature Partner", value: "Portuguese_MaturePartner" },
  { label: "Comedian", value: "Portuguese_Comedian" },
  { label: "Naughty Schoolgirl", value: "Portuguese_NaughtySchoolgirl" },
  { label: "Narrator", value: "Portuguese_Narrator" },
  { label: "Tough Boss", value: "Portuguese_ToughBoss" },
  { label: "Fussy hostess", value: "Portuguese_Fussyhostess" },
  { label: "Dramatist", value: "Portuguese_Dramatist" },
  { label: "Steady Mentor", value: "Portuguese_Steadymentor" },
  { label: "Jovial Man", value: "Portuguese_Jovialman" },
  { label: "Charming Queen", value: "Portuguese_CharmingQueen" },
  { label: "Santa Claus", value: "Portuguese_SantaClaus" },
  { label: "Rudolph", value: "Portuguese_Rudolph" },
  { label: "Arnold", value: "Portuguese_Arnold" },
  { label: "Charming Santa", value: "Portuguese_CharmingSanta" },
  { label: "Charming Lady", value: "Portuguese_CharmingLady" },
  { label: "Ghost", value: "Portuguese_Ghost" },
  { label: "Humorous Elder", value: "Portuguese_HumorousElder" },
  { label: "Calm Leader", value: "Portuguese_CalmLeader" },
  { label: "Gentle Teacher", value: "Portuguese_GentleTeacher" },
  { label: "Energetic Boy", value: "Portuguese_EnergeticBoy" },
  { label: "Reliable Man", value: "Portuguese_ReliableMan" },
  { label: "Serene Elder", value: "Portuguese_SereneElder" },
  { label: "Grim Reaper", value: "Portuguese_GrimReaper" },
  { label: "Assertive Queen", value: "Portuguese_AssertiveQueen" },
  { label: "Whimsical Girl", value: "Portuguese_WhimsicalGirl" },
  { label: "Stressed Lady", value: "Portuguese_StressedLady" },
  { label: "Friendly Neighbor", value: "Portuguese_FriendlyNeighbor" },
  { label: "Caring Girlfriend", value: "Portuguese_CaringGirlfriend" },
  { label: "Powerful Soldier", value: "Portuguese_PowerfulSoldier" },
  { label: "Fascinating Boy", value: "Portuguese_FascinatingBoy" },
  { label: "Romantic Husband", value: "Portuguese_RomanticHusband" },
  { label: "Strict Boss", value: "Portuguese_StrictBoss" },
  { label: "Inspiring Lady", value: "Portuguese_InspiringLady" },
  { label: "Playful Spirit", value: "Portuguese_PlayfulSpirit" },
  { label: "Elegant Girl", value: "Portuguese_ElegantGirl" },
  { label: "Compelling Girl", value: "Portuguese_CompellingGirl" },
  { label: "Powerful Veteran", value: "Portuguese_PowerfulVeteran" },
  { label: "Sensible Manager", value: "Portuguese_SensibleManager" },
  { label: "Thoughtful Lady", value: "Portuguese_ThoughtfulLady" },
  { label: "Theatrical Actor", value: "Portuguese_TheatricalActor" },
  { label: "Fragile Boy", value: "Portuguese_FragileBoy" },
  { label: "Chatty Girl", value: "Portuguese_ChattyGirl" },
  {
    label: "Conscientious Instructor",
    value: "Portuguese_Conscientiousinstructor",
  },
  { label: "Rational Man", value: "Portuguese_RationalMan" },
  { label: "Wise Scholar", value: "Portuguese_WiseScholar" },
  { label: "Frank Lady", value: "Portuguese_FrankLady" },
  { label: "Determined Manager", value: "Portuguese_DeterminedManager" },
  { label: "Level-Headed Man", value: "French_Male_Speech_New" },
  { label: "Patient Female Presenter", value: "French_Female_News Anchor" },
  { label: "Casual Man", value: "French_CasualMan" },
  { label: "Movie Lead Female", value: "French_MovieLeadFemale" },
  { label: "Female Anchor", value: "French_FemaleAnchor" },
  { label: "Male Narrator", value: "French_MaleNarrator" },
  { label: "Sweet Girl", value: "Indonesian_SweetGirl" },
  { label: "Reserved Young Man", value: "Indonesian_ReservedYoungMan" },
  { label: "Charming Girl", value: "Indonesian_CharmingGirl" },
  { label: "Calm Woman", value: "Indonesian_CalmWoman" },
  { label: "Confident Woman", value: "Indonesian_ConfidentWoman" },
  { label: "Caring Man", value: "Indonesian_CaringMan" },
  { label: "Bossy Leader", value: "Indonesian_BossyLeader" },
  { label: "Determined Boy", value: "Indonesian_DeterminedBoy" },
  { label: "Gentle Girl", value: "Indonesian_GentleGirl" },
  { label: "Friendly Man", value: "German_FriendlyMan" },
  { label: "Sweet Lady", value: "German_SweetLady" },
  { label: "Playful Man", value: "German_PlayfulMan" },
  {
    label: "Handsome Childhood Friend",
    value: "Russian_HandsomeChildhoodFriend",
  },
  { label: "Bright Queen", value: "Russian_BrightQueen" },
  { label: "Ambitious Woman", value: "Russian_AmbitiousWoman" },
  { label: "Reliable Man", value: "Russian_ReliableMan" },
  { label: "Crazy Girl", value: "Russian_CrazyQueen" },
  { label: "Pessimistic Girl", value: "Russian_PessimisticGirl" },
  { label: "Attractive Guy", value: "Russian_AttractiveGuy" },
  { label: "Bad-tempered Boy", value: "Russian_Bad-temperedBoy" },
  { label: "Brave Heroine", value: "Italian_BraveHeroine" },
  { label: "Narrator", value: "Italian_Narrator" },
  { label: "Wandering Sorcerer", value: "Italian_WanderingSorcerer" },
  { label: "Diligent Leader", value: "Italian_DiligentLeader" },
  { label: "Kind-hearted girl", value: "Dutch_kindhearted_girl" },
  { label: "Bossy leader", value: "Dutch_bossy_leader" },
  { label: "Kind-hearted girl", value: "Vietnamese_kindhearted_girl" },
  { label: "Calm Woman", value: "Arabic_CalmWoman" },
  { label: "Friendly Guy", value: "Arabic_FriendlyGuy" },
  { label: "Calm Woman", value: "Turkish_CalmWoman" },
  { label: "Trustworthy man", value: "Turkish_Trustworthyman" },
  { label: "Calm Woman", value: "Ukrainian_CalmWoman" },
  { label: "Wise Scholar", value: "Ukrainian_WiseScholar" },
  { label: "Serene Man", value: "Thai_male_1_sample8" },
  { label: "Friendly Man", value: "Thai_male_2_sample2" },
  { label: "Confident Woman", value: "Thai_female_1_sample1" },
  { label: "Energetic Woman", value: "Thai_female_2_sample2" },
  { label: "Male Narrator", value: "Polish_male_1_sample4" },
  { label: "Male Anchor", value: "Polish_male_2_sample3" },
  { label: "Calm Woman", value: "Polish_female_1_sample1" },
  { label: "Casual Woman", value: "Polish_female_2_sample3" },
  { label: "Reliable Man", value: "Romanian_male_1_sample2" },
  { label: "Energetic Youth", value: "Romanian_male_2_sample1" },
  { label: "Optimistic Youth", value: "Romanian_female_1_sample4" },
  { label: "Gentle Woman", value: "Romanian_female_2_sample1" },
  { label: "Thoughtful Mentor", value: "greek_male_1a_v1" },
  { label: "Gentle Lady", value: "Greek_female_1_sample1" },
  { label: "Girl Next Door", value: "Greek_female_2_sample3" },
  { label: "Assured Presenter", value: "czech_male_1_v1" },
  { label: "Steadfast Narrator", value: "czech_female_5_v7" },
  { label: "Elegant Lady", value: "czech_female_2_v2" },
  { label: "Upbeat Man", value: "finnish_male_3_v1" },
  { label: "Friendly Boy", value: "finnish_male_1_v2" },
  { label: "Assetive Woman", value: "finnish_female_4_v1" },
  { label: "Trustworthy Advisor", value: "hindi_male_1_v2" },
  { label: "Tranquil Woman", value: "hindi_female_2_v1" },
  { label: "News Anchor", value: "hindi_female_1_v2" },
];

export const MINIMAX_VOICES = RAW_MINIMAX_VOICES.map((v) => ({
  label: `${v.label} (${getLangCodeForVoiceId(v.value)})`,
  value: v.value,
}));
